name: CI

on: [push]

jobs:
 sast_scan:
    name: Run Bandit 
    run-on: ubuntu-latest

    steps:
    - name: Chcekout code
      uses: actions/checkout@v2

    - name: Set uo Python
      uses: actions/setup-python@v2
      with:
        pyhton_versiob: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r .

      
